# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
        additional_dependencies: [flake8-bugbear, flake8-builtins, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity, Bandit, flake8-pytest-style]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      args:
      - --line-length=88

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
