[build-system]
requires = ['setuptools>=47']
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
testpaths = [
    "tests",
]
